from random import randint

def escolher_random(lista):
    i = randint(0, len(lista) - 1)
    return lista[i]

def biblioteca_br():
    palavras = ['termo', 'negro', 'mexer', 'nobre', 'sobre',
    'algoz', 'plena', 'fazer', 'assim', 'pobre',
    'sobre', 'vigor', 'poder', 'feder', 'cobre',
    'sutil', 'fosse', 'cerne', 'lebre', 'padre',
    'ponto', 'inato', 'quica', 'desde', 'madre',
    'amigo', 'honra', 'torpe', 'pedra', 'lacre',
    'etnia', 'anexo', 'tempo', 'metro', 'noite',
    'bocal', 'lapso', 'expor', 'casal', 'peito',
    'xibiu', 'saber', 'senso', 'gatos', 'pelos',
    'ainda', 'dizer', 'dever', 'tempo', 'jeito',
    'causa', 'temor', 'ceder', 'crivo', 'coser',
    'temer', 'fugaz', 'censo', 'bagre', 'longo',
    'posse', 'prole', 'pudor', 'corta', 'tanga',
    'jeito', 'culto', 'atroz', 'digno', 'haver',
    'vulgo', 'gleba', 'homem', 'todos', 'perde',
    'valha', 'saber', 'dogma', 'beber', 'louco',
    'terno', 'limbo', 'feliz', 'pedir', 'honra',
    'culpa', 'ajuda', 'falso', 'certo', 'falar',
    'servo', 'prosa', 'frito', 'desse', 'presa',
    'posso', 'cunho', 'vital', 'manso', 'culto',
    'belga', 'visar', 'linda', 'nossa', 'forma',
    'acaso', 'fluir', 'afago', 'apelo', 'abrir',
    'garfo', 'praxe', 'golpe', 'tropa', 'matiz',
    'afins', 'trapo', 'pleno', 'crise', 'viver',
    'fluxo', 'ritmo', 'morte', 'senil', 'havia',
    'levar', 'leite', 'cosmo', 'cisma', 'prumo',
    'ouvir', 'pavor', 'brega', 'cabal', 'minha',
    'falta', 'vulto', 'parco', 'bravo', 'favor',
    'pauta', 'vivaz', 'tenro', 'forca', 'peixe',
    'ameno', 'tendo', 'laico', 'grato', 'nicho',
    'rumor', 'sagaz', 'rubro', 'pobre', 'sorte',
    'brisa', 'noite', 'papel', 'libra', 'farsa',
    'muito', 'frase', 'cesta', 'leigo', 'sinto',
    'citar', 'selar', 'lidar', 'ditar', 'dorso',
    'velho', 'seres', 'sonso', 'vazio', 'haste',
    'adiar', 'humor', 'gente', 'ficar', 'tende',
    'morte', 'ideal', 'fonte', 'sulco', 'sinal',
    'premo', 'carta', 'igual', 'marco', 'amplo',
    'canto', 'capaz', 'lavra', 'cuado', 'matos',
    'frase', 'frade', 'lacre', 'opala', 'pouca',
    'pouco', 'prosa', 'lebre', 'febre', 'peles',
    'gente', 'mente', 'lente', 'dente', 'sente',
    'pente', 'jegue', 'gueto', 'minto', 'crina',
    'pilha', 'filha', 'milha', 'linha', 'minha',
    'vinha', 'rolha', 'zorra', 'farra', 'marra',
    'telha', 'velha', 'tripa', 'tropa', 'roupa',
    'volta', 'senta', 'tribo', 'rapar', 'eixos']
    
    return escolher_random(palavras)

def dicionario_letras(letra):
    dicionario = {
        'A': [" █▀█",
              " █▀█",
              " ▀ ▀"],
        'B': [" █▀▄",
              " █▀▄",
              " ▀▀ "],
        'C': [" █▀▀",
              " █  ",
              " ▀▀▀"],
        'Ç': [" █▀▀",
              " █  ",
              " ▀▀▀"],
        'D': [" █▀▄",
              " █ █",
              " ▀▀ "],
        'E': [" █▀▀",
              " █▀▀",
              " ▀▀▀"],
        'F': [" █▀▀",
              " █▀▀",
              " ▀  "],
        'G': [" █▀▀",
              " █ █",
              " ▀▀▀"],
        'H': [" █ █",
              " █▀█",
              " ▀ ▀"],
        'I': [" ▀█▀",
              "  █ ",
              " ▀▀▀"],
        'J': [" ▀▀█",
              "   █",
              " ▀▀ "],
        'K': [" █ █",
              " █▀▄",
              " ▀ ▀"],
        'L': [" █  ",
              " █  ",
              " ▀▀▀"],
        'M': [" █▄█",
              " █ █",
              " ▀ ▀"],
        'N': [" █▀█",
              " █ █",
              " ▀ ▀"],
        'O': [" █▀█",
              " █ █",
              " ▀▀▀"],
        'P': [" █▀█",
              " █▀▀",
              " ▀  "],
        'Q': [" ▄▀▄",
              " █\\█",
              "  ▀\\"],
        'R': [" █▀▄",
              " █▀▄",
              " ▀ ▀"],
        'S': [" █▀▀",
              " ▀▀█",
              " ▀▀▀"],
        'T': [" ▀█▀",
              "  █ ",
              "  ▀ "],
        'U': [" █ █",
              " █ █",
              " ▀▀▀"],
        'V': [" █ █",
              " ▀▄▀",
              "  ▀ "],
        'W': [" █ █",
              " █▄█",
              " ▀ ▀"],
        'X': [" █ █",
              " ▄▀▄",
              " ▀ ▀"],
        'Y': [" █ █",
              "  █ ",
              "  ▀ "],
        'Z': [" ▀▀█",
              " ▄▀ ",
              " ▀▀▀"],
    }
    return dicionario.get(letra.upper(), ["    ", "    ", "    "])
